apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  description: ${{ values.description }}
  tags:
    - python
    - flask
    - postgresql
    - secure-by-default
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: devabm26/${{ values.component_id }}
    dev.redhat.com/devspaces-url: https://devspaces.apps.cluster-6pfqs.6pfqs.sandbox2325.opentlc.com/#https://github.com/devabm26/${{ values.component_id }}
    backstage.io/kubernetes-id: ${{ values.component_id }}
    backstage.io/kubernetes-namespace: thoughts-app 
    janus-idp.io/tekton: ${{ values.component_id }}
  links:
    - url: https://github.com/devabm26/${{ values.component_id }}
      title: View Source
      icon: github
    - url: https://devspaces.apps.cluster-pjx5k.dyn.redhatworkshops.io/#https://github.com/devabm26/${{ values.component_id }}
      title: Open in DevSpaces
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
  providesApis:
    - ${{ values.component_id }}-api


---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.component_id }}-api
  description: REST API for ${{ values.component_id }}
spec:
  type: openapi
  lifecycle: production
  owner: ${{ values.owner }}
  definition:
    $text: ./openapi.yaml
